# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RadarChart' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

pod 'Charts'
#pod 'ChartsRealm'

  # Pods for RadarChart

end
